---
- name: Install PowerShell on Ubuntu
  hosts: dotnetcore
  become: yes

  tasks:
    - name: Update the list of packages
      apt:
        update_cache: yes

    - name: Install pre-requisite packages
      apt:
        name:
          - wget
          - apt-transport-https
          - software-properties-common
        state: present

    - name: Get the version of Ubuntu
      command: "source /etc/os-release && echo $VERSION_ID"
      register: ubuntu_version

    - name: Download the Microsoft repository keys
      get_url:
        url: "https://packages.microsoft.com/config/ubuntu/{{ ubuntu_version.stdout }}/packages-microsoft-prod.deb"
        dest: /tmp/packages-microsoft-prod.deb

    - name: Register the Microsoft repository keys
      apt:
        deb: /tmp/packages-microsoft-prod.deb

    - name: Delete the Microsoft repository keys file
      file:
        path: /tmp/packages-microsoft-prod.deb
        state: absent

    - name: Update the list of packages after adding packages.microsoft.com
      apt:
        update_cache: yes

    - name: Install PowerShell
      apt:
        name: powershell
        state: present
