---
- name: Install and configure GlusterFS on Docker containers
  hosts: docker
  become: true
  tasks:
    - name: Install GlusterFS packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - glusterfs-server
        - glusterfs-client

    - name: Start GlusterFS service
      service:
        name: glusterd
        state: started
        enabled: true

    - name: Install GlusterFS client package on all nodes
      package:
        name: glusterfs-client
        state: present

    - name: Create GlusterFS volume
      gluster_volume:
        state: present
        name: myvolume
        bricks: "{{ gluster_bricks }}"
        replicas: 3
      when: inventory_hostname == groups['docker'][0]

    - name: Mount GlusterFS volume
      mount:
        path: /mnt/gfnode
        src: "{{ groups['docker'][0] }}:/myvolume"
        fstype: glusterfs
        opts: defaults,_netdev
        state: mounted

    - name: Add entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ groups['docker'][0] }}:/myvolume /mnt/gfnode glusterfs defaults,_netdev 0 0"
        state: present

  vars:
    gluster_bricks:
      - "{{ groups['docker'][0] }}:/data/brick1/gv0"
      - "{{ groups['docker'][1] }}:/data/brick1/gv0"
      - "{{ groups['docker'][2] }}:/data/brick1/gv0"
