---
- name: Final assembly of a new ubuntu server before customization
  hosts: new
  become: yes
  vars:
    username: "infra"  
    ssh_keys:
      - files/certs/ansible.pub
      - files/certs/nic-wsl.pub
      - files/certs/brian.pub

  tasks:
    - name: Update the list of packages
      apt:
        update_cache: yes

    - name: Set up SSH to use PAM authentication and limit users
      copy:
        content: |
          PAMAuthenticating yes
          AllowTcpForwarding no
          PermitRootLogin no
          X11Forwarding no
          PermitOpen "sftp"
        dest: /etc/ssh/sshd_config

    - name: Add multiple SSH keys to authorized_keys
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', item) }}"
      with_items: "{{ ssh_keys }}"

    - name: Install pre-requisite packages
      apt:
        name:
          - wget
          - apt-transport-https
          - software-properties-common
          - qemu-guest-agent
          - tpm2-abrmd
          - tpm2-tools
          - libtss2-rc0
        state: present

  handlers:
    - name: restart sshd service
      service:
        name: sshd
        state: restarted