---
- hosts: servers
  become: yes
  vars:
    zabbix_repo_url: "https://repo.zabbix.com/zabbix/{{ ansible_distribution_id }}/release/{{ ansible_distribution_id }}/pool/main/z/zabbix-release/"
    zabbix_repository_package: "zabbix-release_{{ zabbix_version }}+{{ ansible_lsb_codename }}_all.deb"
    zabbix_agent2_package: "zabbix-agent2"
  tasks:
    - name: Install Zabbix repository
      shell: wget {{ zabbix_repo_url }}{{ zabbix_repository_package }} && dpkg -i {{ zabbix_repository_package }}; apt update
      when: ansible_distribution == "Debian" or (ansible_distribution == "Ubuntu" and ansible_lsb_codename in ["buster", "bullseye"])

    - name: Install Zabbix Agent 2 (Debian)
      apt: name={{ zabbix_agent2_package }} state=present
      when: ansible_distribution == "Debian" and not "zabbix-agent2" in package.name
      notify:
        - install Zabbix Agent 2 (Ubuntu)

    - name: Install Zabbix Agent 2 (Ubuntu)
      apt: name={{ zabbix_agent2_package }} state=present
      when: ansible_distribution == "Ubuntu" and not "zabbix-agent2" in package.name
      notify:
        - install Zabbix Agent 2 (Debian)

    - name: Configure Zabbix agent config file
      blockinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        create: false
        block: |
          Server=172.22.158.105
          ListenPort=10050
          ServerActive=172.22.158.105:10051
          Hostname={{ inventory_hostname }}
        insertbefore: '' # Insert at the beginning of the file

    - name: Start Zabbix agent 2 process
      service:
        name: zabbix-agent2
        state: started
        enabled: yes