---
- name: Install and configure Zabbix Agent 2
  hosts: zabbix
  become: yes
  vars:
    zabbix_release_deb_path: /tmp/zabbix-release.deb
    zabbix_repo_map:
      jammy: "https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.2-1+ubuntu22.04_all.deb"
      focal: "https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.2-1+ubuntu20.04_all.deb"
      bookworm: "https://repo.zabbix.com/zabbix/7.2/release/debian/pool/main/z/zabbix-release/zabbix-release_7.2-1+debian12_all.deb"
      bullseye: "https://repo.zabbix.com/zabbix/7.2/release/debian/pool/main/z/zabbix-release/zabbix-release_7.2-1+debian11_all.deb"

  tasks:

    - name: Gather OS release info
      ansible.builtin.setup:
        gather_subset: "!all,min,distribution"

    - name: Set Zabbix repo URL based on codename
      set_fact:
        zabbix_repo_url: "{{ zabbix_repo_map[ansible_distribution_release | lower] }}"
      when: ansible_distribution_release | lower in zabbix_repo_map

    - name: Fail if OS/codename is unsupported
      ansible.builtin.fail:
        msg: "Unsupported OS or codename: {{ ansible_distribution }} {{ ansible_distribution_release }}"
      when: zabbix_repo_url is not defined

    - name: Download Zabbix release package
      ansible.builtin.get_url:
        url: "{{ zabbix_repo_url }}"
        dest: "{{ zabbix_release_deb_path }}"
        mode: "0644"

    - name: Install Zabbix release package
      ansible.builtin.apt:
        deb: "{{ zabbix_release_deb_path }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Zabbix Agent 2
      ansible.builtin.apt:
        name: zabbix-agent2
        state: present

    - name: Configure Zabbix Agent 2
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^{{ item.key }}='
        line: '{{ item.key }}={{ item.value }}'
      loop:
        - { key: 'Server', value: '172.22.158.105' }
        - { key: 'ListenPort', value: '10050' }
        - { key: 'ServerActive', value: '172.22.158.105:10051' }
        - { key: 'Hostname', value: '{{ ansible_hostname }}' }

    - name: Enable and start Zabbix Agent 2
      ansible.builtin.systemd:
        name: zabbix-agent2
        enabled: yes
        state: restarted
